### ISSUE TITLE
in `require': cannot load such file -- nokogiri/nokogiri (LoadError)

### ISSUE THREAD

**Issue by jjgh** [rb2k/viddl-rb#129]
OS: Win 7 x64

> ruby -v

ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]
 
> gem install viddl-rb

```
Fetching: ffi-1.9.8-x64-mingw32.gem (100%)
Successfully installed ffi-1.9.8-x64-mingw32
Fetching: netrc-0.10.3.gem (100%)
Successfully installed netrc-0.10.3
Fetching: unf_ext-0.0.6.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.6
Fetching: unf-0.1.4.gem (100%)
Successfully installed unf-0.1.4
Fetching: domain_name-0.5.23.gem (100%)
Successfully installed domain_name-0.5.23
Fetching: http-cookie-1.0.2.gem (100%)
Successfully installed http-cookie-1.0.2
Fetching: rest-client-1.8.0-x64-mingw32.gem (100%)
Successfully installed rest-client-1.8.0-x64-mingw32
Fetching: multi_json-1.10.1.gem (100%)
Successfully installed multi_json-1.10.1
Fetching: progressbar-0.21.0.gem (100%)
Successfully installed progressbar-0.21.0
Fetching: viddl-rb-1.1.1.gem (100%)
Successfully installed viddl-rb-1.1.1
Parsing documentation for ffi-1.9.8-x64-mingw32
Installing ri documentation for ffi-1.9.8-x64-mingw32
Parsing documentation for netrc-0.10.3
Installing ri documentation for netrc-0.10.3
Parsing documentation for unf_ext-0.0.6
Installing ri documentation for unf_ext-0.0.6
Parsing documentation for unf-0.1.4
Installing ri documentation for unf-0.1.4
Parsing documentation for domain_name-0.5.23
Installing ri documentation for domain_name-0.5.23
Parsing documentation for http-cookie-1.0.2
Installing ri documentation for http-cookie-1.0.2
Parsing documentation for rest-client-1.8.0-x64-mingw32
Installing ri documentation for rest-client-1.8.0-x64-mingw32
Parsing documentation for multi_json-1.10.1
Installing ri documentation for multi_json-1.10.1
Parsing documentation for progressbar-0.21.0
Installing ri documentation for progressbar-0.21.0
Parsing documentation for viddl-rb-1.1.1
Installing ri documentation for viddl-rb-1.1.1
Done installing documentation for ffi, netrc, unf_ext, unf, domain_name, http-cookie, rest-client, multi_json, progressbar, viddl-rb after 11 seconds
10 gems installed
```

> viddl-rb http://www.youtube.com/watch?v=QH2-TGUlwu4

```
C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/viddl-rb-1.1.1/bin/viddl-rb:6:in `<top (required)>'
        from C:/Dev/Ruby22-x64/bin/viddl-rb:23:in `load'
        from C:/Dev/Ruby22-x64/bin/viddl-rb:23:in `<main>'
```

> gem install nokogiri

```
Nokogiri is built with the packaged libraries: libxml2-2.9.2, libxslt-1.1.28, zlib-1.2.8, libiconv-1.14.
Successfully installed nokogiri-1.6.6.2-x64-mingw32
Parsing documentation for nokogiri-1.6.6.2-x64-mingw32
Done installing documentation for nokogiri after 3 seconds
1 gem installed
```

> viddl-rb http://www.youtube.com/watch?v=QH2-TGUlwu4

```
C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/dev/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/viddl-rb-1.1.1/bin/viddl-rb:6:in `<top (required)>'
        from C:/Dev/Ruby22-x64/bin/viddl-rb:23:in `load'
        from C:/Dev/Ruby22-x64/bin/viddl-rb:23:in `<main>'
```

**Comment by primozi** [comment]
Have you found any solutions for this?

**Comment by rb2k** [comment]
Huh, that seems to be a bug in nokogiri on windows from that I can see in the stacktrace.
I don't have a windows install to actually test this on :(

**Comment by jjgh** [comment]
https://github.com/sparklemotion/nokogiri/issues/1256
